### ISSUE TITLE
No such file or directory: 'im_data.npy'

### ISSUE THREAD

**Issue by AlbertoBoem** [abramjos/Scene-boundary-detection#4]
I was trying your code, but when I was running `model.py` with Python 3.7  and I got the following error:

`FileNotFoundError: [Errno 2] No such file or directory: 'im_data.npy'`

**Comment by abramjos** [comment]
Hi that is for testing the data with the ground truth, You will have to create the dataset.

While training the mode, you will need the two arguments, video_file='../dataset_creator/aug_final.mp4',csv_file='../dataset_creator/csv_aug_data.csv'
video_file and csv_file are required which can be created using a sample set of video cuts by the augmentation that was given, which will create the .npy,.csv and .mp4 file.

**Comment by abramjos** [comment]
So you will have to run the sample_video_csv_gen.py with some videos to create a huge augmented dataset.

**Comment by AlbertoBoem** [comment]
Hi thanks for the answers! Basically, I can't figure out how to generate the `im_data.npy` and `cut.npy` files. 

I followed your instructions, but I always get the same error. The output of `sample_video_csv_gen.py` in my case is only: `aug_final.mp4` and `csv_aug_data.csv` .

I run the following scripts in this order:
- `sample_video_csv_gen.py`
- `check_vid.py`
- `datagen.py`
- `model.py`

**Comment by ydwl-lynn** [comment]
> Hi thanks for the answers! Basically, I can't figure out how to generate the `im_data.npy` and `cut.npy` files.
> 
> I followed your instructions, but I always get the same error. The output of `sample_video_csv_gen.py` in my case is only: `aug_final.mp4` and `csv_aug_data.csv` .
> 
> I run the following scripts in this order:
> 
> * `sample_video_csv_gen.py`
> * `check_vid.py`
> * `datagen.py`
> * `model.py`

Excuse me, I also meet the same problem.Did you solve this problem?

**Comment by kukajenny** [comment]
> Hi thanks for the answers! Basically, I can't figure out how to generate the `im_data.npy` and `cut.npy` files.
> 
> I followed your instructions, but I always get the same error. The output of `sample_video_csv_gen.py` in my case is only: `aug_final.mp4` and `csv_aug_data.csv` .
> 
> I run the following scripts in this order:
> 
> * `sample_video_csv_gen.py`
> * `check_vid.py`
> * `datagen.py`
> * `model.py`

I have solved the problem. The output of sample_video_csv_gen.py is only: aug_final.mp4 and csv_aug_data.csv. The generation of im_data.npy file is performed in model.py (try, except). Just follow the order of the scripts and change the path of video_file and csv_file in model.py to your corresponding path. The reason for the error is that the path generated by sample_video_csv_gen.py is the same directory by default, and the directory in model.py is under dataset_creator.
